- name: installing redis component
  hosts: redis
  become: yes
  tasks:
  - name: installing redis rpm
    asible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
      state: insatalled
      
  - name: module to enable
    ansible.builtin.shell: yum module enable redis:remi-6.2 -y
  
  - name: installing redis 
    ansible.builtin.yum:
      name: redis 
      state: isntalled

  - name: replacing 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: enable and stat redis
    ansible.builtin.service:
      name: redis
      enabled: yes
      state: started

  
