- name: installing user component
  hosts: user
  become: yes
  tasks:
  - name: Setup NodeJs
    ansible.builtin.shell: 'curl -sL https://rpm.nodesource.com/setup_lts.x | bash'
  
  - name: installing NodeJs
    ansible.builtin.yum:
      name: nodejs 
      state: installed
  
  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop

  - name: creating a app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: downloading and unziping artifact
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /app
      remote_src: yes
  
  - name: npm installing
    ansible.builtin.shell: npm install 
    args:
    chdir: /app
    
  - name: coping user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reloading
    ansible.builtin.systemd_service:
      name: user
      state: reload
      ignore_errors: true

  - name: enable and statring user
    ansible.builtin.service:
      name: user
      enabled: yes
      state: started
  
  - name: coping mongo repo
    ansible.builtin.service:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: isntalling mongodb-org-shell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: conneting to mongodb host
    ansible.builtin.shell: mongo --host mongodb.venkateshamsonnalia143.online </app/schema/user.js 

      


