- name: install web component
  hosts: web
  become: yes
  tasks:
  - name: inatall nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
      
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: download and unzip web artifact
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: Copying roboshop conf
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 

  - name: restarting nginx
    ansible.builtin.service:
      name: nginx
      state: restarted